# Generated by Django 6.0.2 on 2026-02-26 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500, verbose_name='Тема урока')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Токенов в запросе')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Токенов в ответе')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.grade', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Запрос на генерацию',
                'verbose_name_plural': 'Запросы на генерацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx_file', models.FileField(upload_to='generated/docx/%Y/%m/%d/', verbose_name='Word документ')),
                ('pptx_file', models.FileField(upload_to='generated/pptx/%Y/%m/%d/', verbose_name='PowerPoint презентация')),
                ('docx_text', models.TextField(verbose_name='Текст документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='generator.generationrequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('grades', models.ManyToManyField(to='generator.grade', verbose_name='Классы')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.subject', verbose_name='Предмет'),
        ),
    ]
